
import = [
    # "~/.config/alacritty/rose-pine.toml"
#    "~/.config/alacritty/catppuccin-mocha.toml"
    "~/.config/alacritty/vscode.toml"
]

[cursor]
style = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[hints.enabled]]
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.command]
args = []
program = "/home/minno/.config/alacritty/scripts/copy_link.sh"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "ScrollLineUp"
# key = "K"
# mods = "Control"
# 
# [[keyboard.bindings]]
# action = "ScrollLineDown"
# key = "J"
# mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[window]
opacity = 1.0

[env]
TERM = "xterm-256color"
